### ISSUE TITLE
Incorrect redirect after payment validation

### ISSUE THREAD

**Issue by sdebacker** [TypiCMS/Subscriptions#2]
After validating a payment on Mollie, we are redirected to /fr/webhooks/cashier/check-payment which is a 404 page.

**Comment by AlexisSerneels** [comment]
Can not reproduce. Please ensure /config/cashier.php is set to:
`'redirect_url' => config('app.url').'/webhooks/cashier/check-payment',`

**Comment by sdebacker** [comment]
I could solve this by setting adding {payment_id} on the redirect URL:
`'redirect_url' => config('app.url').'/webhooks/cashier/check-payment/{payment_id}',`
