### ISSUE TITLE
Download of an invoice cause an exception (DOMPDF)

### ISSUE THREAD

**Issue by sdebacker** [TypiCMS/Subscriptions#7]

**Comment by AlexisSerneels** [comment]
Seems to be linked to: https://github.com/PhenX/php-font-lib/pull/76 and https://github.com/dompdf/dompdf/issues/2091
Would simply disable the Download feature for now and let people use the Print PDF browser feature.

**Comment by sdebacker** [comment]
Fixed by a package update.
